[build]
builder = "NIXPACKS"
buildCommand = "npm install --prefix backend"

[deploy]
startCommand = "node backend/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"
healthcheckTimeout = 500
